import { Octokit } from '@octokit/rest';

type GeneratedFile = { path: string; content: string };

export interface GitHubPushResult {
  repoUrl: string;
  repoName: string;
  isNew: boolean;
  owner: string;
}

export class GitHubService {
  async pushToGitHub(
    githubToken: string,
    repoName: string,
    files: GeneratedFile[],
    isPrivate: boolean = false
  ): Promise<GitHubPushResult> {
    const octokit = new Octokit({ auth: githubToken });

    const { data: user } = await octokit.rest.users.getAuthenticated();
    const owner = user.login;

    const cleanRepoName = repoName
      .toLowerCase()
      .replace(/[^a-z0-9-_]/g, '-')
      .replace(/^-+/, '')
      .replace(/-+$/, '');

    if (!cleanRepoName) {
      throw new Error('Invalid repository name');
    }

    let repoExists = false;
    try {
      await octokit.rest.repos.get({ owner, repo: cleanRepoName });
      repoExists = true;
    } catch {
      repoExists = false;
    }

    if (!repoExists) {
      await octokit.rest.repos.createForAuthenticatedUser({
        name: cleanRepoName,
        description: 'Generated by IDEA Platform',
        private: isPrivate,
        auto_init: true
      });

      await new Promise((resolve) => setTimeout(resolve, 1200));
    }

    const { data: repo } = await octokit.rest.repos.get({
      owner,
      repo: cleanRepoName
    });
    const defaultBranch = repo.default_branch || 'main';

    const { data: refData } = await octokit.rest.git.getRef({
      owner,
      repo: cleanRepoName,
      ref: `heads/${defaultBranch}`
    });

    const latestCommitSha = refData.object.sha;

    const { data: commitData } = await octokit.rest.git.getCommit({
      owner,
      repo: cleanRepoName,
      commit_sha: latestCommitSha
    });

    const baseTreeSha = commitData.tree.sha;

    const treeItems = await Promise.all(
      files.map(async (file) => {
        const { data: blob } = await octokit.rest.git.createBlob({
          owner,
          repo: cleanRepoName,
          content: Buffer.from(file.content).toString('base64'),
          encoding: 'base64'
        });

        return {
          path: file.path,
          mode: '100644' as const,
          type: 'blob' as const,
          sha: blob.sha
        };
      })
    );

    const { data: newTree } = await octokit.rest.git.createTree({
      owner,
      repo: cleanRepoName,
      base_tree: baseTreeSha,
      tree: treeItems
    });

    const { data: newCommit } = await octokit.rest.git.createCommit({
      owner,
      repo: cleanRepoName,
      message: repoExists
        ? 'Update: regenerated by IDEA Platform'
        : 'Initial commit: generated by IDEA Platform',
      tree: newTree.sha,
      parents: [latestCommitSha]
    });

    await octokit.rest.git.updateRef({
      owner,
      repo: cleanRepoName,
      ref: `heads/${defaultBranch}`,
      sha: newCommit.sha
    });

    return {
      repoUrl: `https://github.com/${owner}/${cleanRepoName}`,
      repoName: cleanRepoName,
      isNew: !repoExists,
      owner
    };
  }

  async verifyToken(
    githubToken: string
  ): Promise<{ valid: boolean; username?: string }> {
    try {
      const octokit = new Octokit({ auth: githubToken });
      const { data: user } = await octokit.rest.users.getAuthenticated();
      return { valid: true, username: user.login };
    } catch {
      return { valid: false };
    }
  }
}

export const githubService = new GitHubService();
